# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.chatLayout = QtWidgets.QVBoxLayout()
        self.chatLayout.setObjectName("chatLayout")
        self.chatDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.chatDisplay.setReadOnly(True)
        self.chatDisplay.setObjectName("chatDisplay")
        self.chatLayout.addWidget(self.chatDisplay)
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.inputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputBox.setObjectName("inputBox")
        self.inputLayout.addWidget(self.inputBox)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.inputLayout.addWidget(self.sendButton)
        self.chatLayout.addLayout(self.inputLayout)
        self.mainLayout.addLayout(self.chatLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.mainLayout.addWidget(self.label)
        self.logoView = QtWidgets.QGraphicsView(self.centralwidget)
        self.logoView.setObjectName("logoView")
        self.mainLayout.addWidget(self.logoView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IsaKaiHBG_AI - Sovereign Multi-Agent AI"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
